version: '3.11'

services:
  frontend:
    build:
      context: ./src
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./server:/app
    ports:
      - "8001:8001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
