services:
  neo4j:
    image: neo4j:5.20.0
    ports:
      - "7474:7474" # Neo4j Browser
      - "7687:7687" # Bolt protocol
    environment:
      NEO4J_AUTH: neo4j/hello123 # Set initial password here
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes" # Accept Neo4j license agreement
    healthcheck:
      test: wget http://localhost:7474 || exit 1
      interval: 10s
      timeout: 10s
      retries: 10

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      neo4j:
        condition: service_healthy
